#!/usr/bin/python
import math
import time

def isPrime(n):
    if n==1:
        return False
    elif n<4: # 2 and 3 are prime
        return True
    elif n%2==0:
        return False
    elif n<9: #4, 6 and 8 are already excluded
        return True
    elif n%3==0:
        return False
    else:
        r=int(math.sqrt(n))
        f=5
        while f<=r:
            if n%f==0:
                return False
            elif n%(f+2)==0:
                return False
            f+=6
        return True
    
def main():
    suma = 0
    for n in range(1,2000000):
        if isPrime(n):
            suma+=n
    print suma

if __name__ == "__main__":
    start_time = time.time()
    main()
    print("--- %s seconds ---" % (time.time() - start_time))
            
