#!/usr/bin/python
import math
import sys

a = 0
b = 0
c = 0
while True:
    for a in range (1 , 1000):
        for b in range(1,1000):
             if (a + b + math.sqrt(a*a + b*b)) == 1000:
                 c = math.sqrt(a*a + b*b)
                 print a*b*c
                 sys.exit()
