#!/usr/bin/env python

def SquaresOfNaturalNumbers(start, end):
    suma=0
    for x in range(start, end+1):
        suma+=x*x
    return suma

def SquareOfSumOfNaturalNumbers(start, end):
    suma = 0
    for x in range(start, end+1):
        suma+=x
    return suma*suma

def main():
    squares = SquaresOfNaturalNumbers(1,100)
    suma = SquareOfSumOfNaturalNumbers(1,100)
    print "Result is: {0}.".format(suma-squares)

if __name__ == "__main__": main()
