#!/usr/bin/python
st = 10000
while True:
        times=0
        for x in range(1,21):
               if(st%x == 0):
                       times+=1
        #print times
        if(times == 20):
                print st
                break
        st+=1
